### ISSUE TITLE
Only available in GHE Cloud

### ISSUE THREAD

**Issue by arcsector** [splunk/github-audit-log-monitoring-add-on-for-splunk#14]
The documentation says:

>### Prerequisites
> - Splunk Heavy Forwarder v8.0+
> - Python 3.7+
> - GitHub Enterprise Cloud

I'm wondering whether or not GHE Cloud is needed, or if you can use GHE on-prem as well for this application - it's not clear from the docs whether this is supported, or if GHE on-prem customers need to upgrade to a certain version before using, etc...

**Comment by derkkila-splunk** [comment]
This Add-On is specific to GHE Cloud as the required APIs are not present on GHE On-Prem. GHE On-Prem however has a built in method of sending logs to Splunk through Syslog. If you are looking to use GHE Server/On-Prem please email me: first part of my username at splunk.
