### ISSUE TITLE
Error running in Splunk Cloud on IDM server

### ISSUE THREAD

**Issue by larrys** [splunk/github-audit-log-monitoring-add-on-for-splunk#16]
Here is the error message:
```03-14-2022 20:58:00.323 +0000 ERROR ExecProcessor [19747 ExecProcessor] - message from "/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/github-audit-log-monitoring-add-on-for-splunk/bin/ghe_audit_log_monitoring.py" RuntimeError: Could not fetch audit log data. Please check your configuration, access token scope / correctness and API rate limits. status_code: 403 - url: https://api.github.com/enterprises/myriadgenetics/audit-log?phrase=&include=all&after=&before=&order=asc&per_page=100 - Response: {"message":"Must have admin rights to Repository.","documentation_url":"https://docs.github.com/rest/reference/enterprise-admin#get-the-audit-log-for-an-enterprise"}```

It has `admin:enterprise` permission. We have not hit our rate either. What else can I look for or at?

Thanks

**Comment by derkkila-splunk** [comment]
The PAT needs to be generated by an Enterprise owner to have access to the audit logs.
