### ISSUE TITLE
Github add-on Error with Data Inputs

### ISSUE THREAD

**Issue by bitfluencer** [splunk/github-audit-log-monitoring-add-on-for-splunk#17]
Hello Team!

I have configured the github-audit-log-monitoring-add-on-for-splunk with and continuously getting below errors, can someone please help me here?

03-25-2022 04:10:07.349 +0000 ERROR ExecProcessor [6894 ExecProcessorSchedulerThread] - message from "/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/github-audit-log-monitoring-add-on-for-splunk/bin/ghe_audit_log_monitoring.py" requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /enterprises/XXX/audit-log?phrase=&include=all&after=&before=&order=asc&per_page=100 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb26fa058d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
--

**Comment by derkkila-splunk** [comment]
can you please email me at derkkila@splunk.com please

**Comment by derkkila-splunk** [comment]
Support for this add-on is going to be retired in favor of a new Add-On: https://splunkbase.splunk.com/app/6254/
