### ISSUE TITLE
Download link not working...

### ISSUE THREAD

**Issue by s-carbone** [splunk/github-audit-log-monitoring-add-on-for-splunk#3]
👋🏼  @derkkila @derkkila-splunk - has the download location moved from https://splunkbase.splunk.com/app/5595/?  Thanks!

**Comment by s-carbone** [comment]
ping - have a joint customer looking to use the add on and unable to download - what are we missing?  Thanks!

**Comment by derkkila-splunk** [comment]
Hi Steve, hit a snag with the Splunkbase release, please email me and I can get you set up.

**Comment by s-carbone** [comment]
thanks @derkkila-splunk 🙇🏼‍♂️

**Comment by derkkila-splunk** [comment]
The app was approved on Splunkbase so the download link should work now.
