### ISSUE TITLE
Enhancement request: Adding the name of the inputs (stanza name) into logs

### ISSUE THREAD

**Issue by jenipherc** [splunk/github-audit-log-monitoring-add-on-for-splunk#7]
It would be easier to trace / troubleshoot if the stanza name  or the input name is showing up in the logs. We were troubleshooting 2 failed inputs, and it was a bit difficult to know which log event is associated with which input.

**Comment by derkkila-splunk** [comment]
I am adding that functionality to the next release. Ran into a similar issue myself so added it to a testing version and will be adding the code soon.

**Comment by derkkila-splunk** [comment]
Included in the last release
