### ISSUE TITLE
Enhancement Request: Allow configuring an index that doesn't reside on the Splunk Enterprise where this add-on resides

### ISSUE THREAD

**Issue by jenipherc** [splunk/github-audit-log-monitoring-add-on-for-splunk#8]
We place this add-on onto a heavy forwarder for data collection, and then send data to indexer cluster where indexes reside. Therefore, when we configure the data input in UI, the index we want to send data to doesn't exist, and not available to select in the drop down menu. Even if we modify the inputs.conf manually and change the index name, the data will be not forwarded. 

We ended up creating an index locally where the Add-on is installed, and because of the outputs.conf is set to forward (and not indexed locally), this allows the Add-on to send data to the index reside in our indexer cluster.

**Comment by derkkila-splunk** [comment]
Support for this add-on is being sunset in favor of a new Add-on: https://splunkbase.splunk.com/app/6254/
